POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "password123"
}

###
POST http://localhost:3000/register
Content-Type: application/json

{
  "name":"jatin kumar",
  "email": "jatin@example.com",
  "password": "jatin123"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "jatin@example.com",
  "password": "jatin123"
}

###

###

POST http://localhost:3000/register
Content-Type: application/json

{
  "name": "John2 Bhaina",
  "email": "johnbhaina2@example.com",
  "password": "password1232"
}

###
GET http://localhost:3000/users
###
POST http://localhost:3000/cart/1
Content-Type: application/json
{
  "id":1,
  "quantity":1
}


###
GET http://localhost:3000/products/
Content-Type: application/json

###
POST http://localhost:3000/register
Content-Type: application/json

{
  "name":"aman",
  "email": "aman@example.com",
  "password": "aman123"
}
###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "aman@example.com",
  "password": "aman123"
}
###


